on:
  push:
    tags:
      - '*'
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Run tests
      run: mdbook build #&& mdbook test
    - name: Deploy GitHub Pages
      run: |
        mdbook build
        git worktree add website
        git config user.name "Deploy from CI"
        git config user.email "git@git"
        cd website
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/website
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to website"
        git push --force --set-upstream origin website

