on: [push]
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.25/mdbook-v0.4.25-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Run tests
      run: mdbook test && mdbook build 
    - name: Deploy GitHub Pages
      run: |
        git worktree add /tmp/website website
        rm -rf /tmp/website/*
        cp -rp book/* /tmp/website/
        cd /tmp/website
        git add -A
        git commit -m "Deploy $GITHUB_SHA to website" || echo "No changes to commit"
        git push origin website